### ISSUE TITLE
Support for Iso9660 entries bigger than 2GB

### ISSUE THREAD

**Issue by JuliusNguyen** [stephenc/java-iso-tools#23]
Hey!
I tried to read a large entry (> 2GB) from an iso9660 file using Iso9660FileSystem.

The stream of the entry (as a result of Iso9660FileSystem.getInputStream(..)) returned a size of -2147483648 bytes. This looks a lot like a casting issue, where a long is casted to int, causing some kind of overflow. As a result of that, EntryInputStream.read(..) does not read any bytes and just returns -1.

Is the 2GB limitation a design decision?

**Comment by stephenc** [comment]
should be fixed in 2.1.0 but 🤷
