### ISSUE TITLE
2.0.2 release plans?

### ISSUE THREAD

**Issue by nishihatapalmer** [stephenc/java-iso-tools#24]
Are there any plans for a 2.0.2 release? 

The SeekableInput interface is something we'd like to use.   We could always fork the code if necessary - but how stable is the 2.0.2-SNAPSHOT code right now?

**Comment by stephenc** [comment]
2.1.0 released and project status badge added to readme. any subsequent releases just depends on whether I have time and whether the release is low cost to make
